# Production environment configuration. These should generally receive values
# in settings.local.yml for deployed instances. If running a multi-environment
# instance for testing or debugging, production.local.yml may be helpful. As-is,
# they are compatible with a typical container-style approach, where default
# ports on generic hostnames are used for each service/resource.

hostname: <%= ENV['APP_HOSTNAME'] || 'heliotropium.local' %>

rails:
  database:
    database: heliotropium
  # Set the key base in settings.local.yml or production.local.yml or use the
  # SECRET_KEY_BASE environment variable, which will take precedence. It is
  # left nil here to trigger the error message from Rails if not specified.
  secret_key_base:

