name: testing-delete-all-svc-deploy-po

on: workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    environment: fulcrum-testing
    steps:
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
      - name: Authenticate with kubernetes
        run: |
          mkdir -p ${HOME}/.kube/certs/cluster
          echo ${{ secrets.CA_CRT_BASE64 }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
          kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=`echo ${{ secrets.SERVER_URL_BASE64 }} | base64 -d`
          kubectl config set-credentials default --token=`echo ${{ secrets.TOKEN_BASE64 }} | base64 -d`
          kubectl config set-context default --cluster=cluster --user=default --namespace=`echo ${{ secrets.NAMESPACE_BASE64 }} | base64 -d`
          kubectl config use-context default
          kubectl config view
          kubectl config current-context
      - name: Kubectl delete all
        run: |
          kubectl delete deployments --all
          kubectl delete services --all
          kubectl delete pods --all